#pragma once

#include "NifFile.h"
#include "Param_Infos.h"

enum {
	kNiTexingPropAct_SetTexCount,
	kNiTexingPropAct_AddTex,
	kNiTexingPropAct_DelTex,
	kNiTexingPropAct_SetClampMode,
	kNiTexingPropAct_SetFilterMode,
	kNiTexingPropAct_SetFlags,
	kNiTexingPropAct_SetUVSet,
	kNiTexingPropAct_SetHasTransf,
	kNiTexingPropAct_SetTransl,
	kNiTexingPropAct_SetTiling,
	kNiTexingPropAct_SetRot,
	kNiTexingPropAct_SetCenOff
};

extern CommandInfo kCommandInfo_NiTexturingPropertyGetTextureCount;
extern CommandInfo kCommandInfo_NiTexturingPropertySetTextureCount;
extern CommandInfo kCommandInfo_NiTexturingPropertyHasTexture;

extern CommandInfo kCommandInfo_NiTexturingPropertyGetTextureSource;
extern CommandInfo kCommandInfo_NiTexturingPropertyAddTextureSource;
extern CommandInfo kCommandInfo_NiTexturingPropertyDeleteTextureSource;

extern CommandInfo kCommandInfo_NiTexturingPropertyGetTextureClampMode;
extern CommandInfo kCommandInfo_NiTexturingPropertyGetTextureFilterMode;
extern CommandInfo kCommandInfo_NiTexturingPropertyGetTextureUVSet;
extern CommandInfo kCommandInfo_NiTexturingPropertyTextureHasTransform;
extern CommandInfo kCommandInfo_NiTexturingPropertyGetTextureTranslation;
extern CommandInfo kCommandInfo_NiTexturingPropertyGetTextureTiling;
extern CommandInfo kCommandInfo_NiTexturingPropertyGetTextureRotation;
extern CommandInfo kCommandInfo_NiTexturingPropertyGetTextureCenterOffset;

extern CommandInfo kCommandInfo_NiTexturingPropertySetTextureClampMode;
extern CommandInfo kCommandInfo_NiTexturingPropertySetTextureFilterMode;
extern CommandInfo kCommandInfo_NiTexturingPropertySetTextureUVSet;
extern CommandInfo kCommandInfo_NiTexturingPropertySetTextureHasTransform;
//extern CommandInfo kCommandInfo_NiTexturingPropertySetTextureTranslation;
//extern CommandInfo kCommandInfo_NiTexturingPropertySetTextureTiling;
extern CommandInfo kCommandInfo_NiTexturingPropertySetTextureRotation;
//extern CommandInfo kCommandInfo_NiTexturingPropertySetTextureCenterOffset;

/*
extern CommandInfo kCommandInfo_NiAlphaPropertyGetBlendState;
extern CommandInfo kCommandInfo_NiAlphaPropertyGetSourceBlendFunction;
extern CommandInfo kCommandInfo_NiAlphaPropertyGetDestinationBlendFunction;
extern CommandInfo kCommandInfo_NiAlphaPropertyGetTestState;
extern CommandInfo kCommandInfo_NiAlphaPropertyGetTestFunction;
extern CommandInfo kCommandInfo_NiAlphaPropertyGetTestThreshold;
extern CommandInfo kCommandInfo_NiAlphaPropertyGetTriangleSortMode;
extern CommandInfo kCommandInfo_NiAlphaPropertyGetFlags;

extern CommandInfo kCommandInfo_NiAlphaPropertySetBlendState;
extern CommandInfo kCommandInfo_NiAlphaPropertySetSourceBlendFunction;
extern CommandInfo kCommandInfo_NiAlphaPropertySetDestinationBlendFunciton;
extern CommandInfo kCommandInfo_NiAlphaPropertySetTestState;
extern CommandInfo kCommandInfo_NiAlphaPropertySetTestFunction;
extern CommandInfo kCommandInfo_NiAlphaPropertySetTestThreshold;
extern CommandInfo kCommandInfo_NiAlphaPropertySetTriangleSortMode;
extern CommandInfo kCommandInfo_NiAlphaPropertySetFlags;
*/